# Generated by Django 5.1.5 on 2025-02-01 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_faq_answer_bn_faq_answer_hi_faq_question_bn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='answer_bn',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer_hi',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_bn',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_hi',
        ),
    ]
