# Generated by Django 5.1.5 on 2025-01-31 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_faq_answer_bn_faq_answer_hi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
